# Generated by Django 5.2.1 on 2025-06-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='id',
        ),
        migrations.AddField(
            model_name='todo',
            name='no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
